### ISSUE TITLE
Pages that produce completely empty index entries cause an internal error

### ISSUE THREAD

**Issue by akavel** [PataphysicalSociety/soupault#45]
## Steps to reproduce

On Windows (didn't try on Linux).

Note: the weird powershell stuff is just to convert CRLF -> LF so that `git apply` can consume it successfully.

Note also the `^Z` (i.e. <kbd>Ctrl-Z</kbd>, <kbd>Enter</kbd>) at the end of the file, it's needed to close the `copy CON` operation successfully.

This appears to be a minimal reproducer; if I remove any of the entries in soupault.toml, or the foo.html file, there's no error. Also it seems to error if foo.html is named foo.md instead.

```
C:> soupault --version
soupault 4.0.0
Copyright 2022 Daniil Baturin et al.
soupault is free software distributed under the MIT license
Visit https://www.soupault.app/reference-manual for documentation

C:> git init bug
C:> cd bug
C:> soupault --init

C:> copy CON bug.patch
diff --git a/site/foo.html b/site/foo.html
new file mode 100644
index 0000000..e69de29
diff --git a/soupault.toml b/soupault.toml
index 7e750c9..144462c 100644
--- a/soupault.toml
+++ b/soupault.toml
@@ -59,7 +59,8 @@
 
   # You can choose where exactly to insert the content in its parent element.
   # The default is append_child, but there are more, including prepend_child and replace_content
-  default_content_action = "append_child"
+  # default_content_action = "append_child"
+  default_content_action = "replace_content"
 
   # If a page already has a document type declaration, keep the declaration
   keep_doctype = true
@@ -120,3 +121,14 @@
   # By default this widget deletes all elements matching the selector,
   # but you can set this option to false to delete just the first one
   delete_all = true
+
+[index]
+  index = true
+
+
+
+[hooks.post-index]
+  lua_source = '''
+    -- nothing
+  '''
+
^Z

C:> powershell.exe -noninteractive -NoProfile -ExecutionPolicy Bypass -Command "& {[IO.File]::WriteAllText('bug2.patch', ([IO.File]::ReadAllText('bug.patch') -replace \"`r`n\", \"`n\"))};"

C:> git apply bug2.patch
bug2.patch:32: new blank line at EOF.
+
warning: 1 line adds whitespace errors.

C:> soupault --debug
[DEBUG] Widget processing order: generator-meta page-title no-blink
[INFO] Build directory "build" does not exist, creating
[INFO] Processing page site\foo.html
[INFO] Using the default template for page site\foo.html
[DEBUG] Not inserting index data: page name does not match index
[INFO] Running the "post-index" hook on page site\foo.html
[INFO] Running the post-index hook on page site\foo.html
[ERROR] soupault encountered an internal error: post-index hook got a JSON value that isn't an object.
[ERROR] Please report a bug and attach the message and the exception trace to your report.
Fatal error: exception Dune__exe__Soupault_common.Internal_error("post-index hook got a JSON value that isn't an object")
Raised at Dune__exe__Soupault_common.internal_error in file "src/soupault_common.ml", line 21, characters 5-31
Called from Dune__exe__Hooks.run_post_index_hook.assoc_of_json in file "src/hooks.ml", line 112, characters 11-81
Called from Dune__exe__Soupault.extract_metadata in file "src/soupault.ml", line 348, characters 6-112
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 433, characters 21-68
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 444, characters 8-77
Called from Dune__exe__Soupault.process_page_files.(fun) in file "src/soupault.ml", line 623, characters 15-73
Called from Dune__exe__Utils.fold_left in file "src/utils.ml", line 74, characters 15-22
Called from Dune__exe__Soupault.main in file "src/soupault.ml", line 752, characters 21-91
Called from Dune__exe__Soupault in file "src/soupault.ml", line 774, characters 12-19

**Comment by dmbaturin** [comment]
[soupault-4.0.1-alpha1.exe.zip](https://github.com/PataphysicalSociety/soupault/files/8789017/soupault-4.0.1-alpha1.exe.zip)

This is really interesting. I thought that it's a completely impossible situation so I never even thought to log the real value. I attached a build with a change to log it in JSON (238234450a86).

That build also includes the fix for #44.

Ideally I'd like to have a complete source of that website to experiment with, but first could you run it with the test build and show me the output? Maybe that will give me enough information to attempt a fix.

**Comment by akavel** [comment]
> That build also includes the fix for https://github.com/PataphysicalSociety/soupault/issues/44.

Fixes it for me, thanks! ❤️ 

> Ideally I'd like to have a complete source of that website to experiment with (...)

Hm; FWIW, the scenario I described above *does* deterministically reproduce the bug on my machine. Please note the patch to `soupault.yaml` and to `site/foo.html` (new file creation). So I think you should be able to experiment with it if you follow the steps, no? Possibly even on non-Windows OS (replacing `copy CON bug.patch` with `cat > bug.patch <<EOF`, etc). Or does it not reproduce on your machine if you follow the steps?

Regardless, the output from the executable when run with the reproducer scenario:

```
C:\prog\tmp\bug4>\dnload\tmp\soupault-4.0.1-alpha1.exe --debug
[DEBUG] Widget processing order: generator-meta page-title no-blink
[INFO] Processing page site\foo.html
[INFO] Using the default template for page site\foo.html
[DEBUG] Not inserting index data: page name does not match index
[INFO] Running the "post-index" hook on page site\foo.html
[INFO] Running the post-index hook on page site\foo.html
[ERROR] soupault encountered an internal error: post-index hook got a JSON value that isn't an object:
 [].
[ERROR] Please report a bug and attach the message and the exception trace to your report.
Fatal error: exception Dune__exe__Soupault_common.Internal_error("post-index hook got a JSON value that isn't an object:\n []")
Raised at Dune__exe__Soupault_common.internal_error in file "src/soupault_common.ml", line 21, characters 5-31
Called from Dune__exe__Hooks.run_post_index_hook.assoc_of_json in file "src/hooks.ml", line 112, characters 11-139
Called from Dune__exe__Soupault.extract_metadata in file "src/soupault.ml", line 348, characters 6-112
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 433, characters 21-68
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 444, characters 8-77
Called from Dune__exe__Soupault.process_page_files.(fun) in file "src/soupault.ml", line 623, characters 15-73
Called from Dune__exe__Utils.fold_left in file "src/utils.ml", line 74, characters 15-22
Called from Dune__exe__Soupault.main in file "src/soupault.ml", line 752, characters 21-91
Called from Dune__exe__Soupault in file "src/soupault.ml", line 774, characters 12-19
```

**Comment by dmbaturin** [comment]
@akavel  Simply setting `default_content_action = "replace_content"` and adding an empty post-index hook doesn't crash soupault for me on Linux. Am I missing an important step?

It's really strange that in your case it receives an empty list though, this does indicate a logic bug somewhere in my code, I just need to find where it is and what causes it.

**Comment by akavel** [comment]
There's 4 elements that must all happen, any on missing removes the error:

1. default_content
2. index
3. post_index (with lua, I think; I didn't try keeping the sections but removing the values)
4. empty file at `site/foo.html`

**Comment by dmbaturin** [comment]
@akavel Sorry, I missed the empty page part. I can reproduce it indeed, thanks for pointing it out! I'll look into it and let you know when I have a fix.

**Comment by dmbaturin** [comment]
[soupault-4.0.1-alpha2.zip](https://github.com/PataphysicalSociety/soupault/files/8789615/soupault-4.0.1-alpha2.zip)

I think I've found the problem. It's likely related to the ambiguity of projecting Lua tables back to OCaml (e1424b784cd7e946c8ebd5). Could you try the attached build?

**Comment by akavel** [comment]
> [soupault-4.0.1-alpha2.zip](https://github.com/PataphysicalSociety/soupault/files/8789615/soupault-4.0.1-alpha2.zip)
> 
> I think I've found the problem. It's likely related to the ambiguity of projecting Lua tables back to OCaml ([e1424b7](https://github.com/PataphysicalSociety/soupault/commit/e1424b784cd7e946c8ebd5634a3c7d646465267a)). Could you try the attached build?

Yep, that appears to fix the problem, thanks! :)
