### ISSUE TITLE
Tag latest release?

### ISSUE THREAD

**Issue by woutermont** [PataphysicalSociety/soupault#54]
As the title says: it would be handy if scripts could just reference a latest release URL, e.g. by updating a `latest` tag on GH Releases and/or having a `/latest` URL in your release directory.

**Comment by dmbaturin** [comment]
Oh, I was just going to do a bit more testing before I tag it. I'm going to upload the binaries today, then tag the release and make an OPAM repository PR.

Sorry for the somewhat messy process.

**Comment by dmbaturin** [comment]
The new release is done now, with a tag and official binaries: https://soupault.app/blog/soupault-4.7.0-release
