### ISSUE TITLE
Generator mode inserts second <body> if first tag of partial is <style>

### ISSUE THREAD

**Issue by delan** [PataphysicalSociety/soupault#58]
I like using generator mode for templating, and I often put a \<style> at the beginning of a partial for styles local to that page. Unfortunately this causes a second \<body> tag to get inserted between that \<style> and any ordinary body content, unless I put a dummy element that “belongs” in \<body> before the \<style>.

I wonder if this has something to do with the parsing behaviour of \<style>, where it [normally goes in \<head> unless the \<body> has started](https://html.spec.whatwg.org/multipage/#optional-tags:the-body-element). I haven’t looked at the code, but it sounds like we parse site files to check if they’re partial or complete, then merge the parsed page into the parsed template, which already has a \<body> (implied or otherwise)?

```toml
# soupault.toml
[settings]
  generator_mode = true
  pretty_print_html = false
```
```html
<!-- templates/main.html -->
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body></body>
</html>
```
```html
<!-- site/index.html -->
<!-- bug no longer happens with <div></div> here -->
<style>p { color: green; }</style>
<p>Hello, world!
```
```html
<!-- build/index.html -->
<!DOCTYPE html>
<html><head>
        <meta charset="utf-8">
    </head>
    <body>

<style>p { color: green; }</style>
<body><p>Hello, world!
</p></body></body></html>
```

**Comment by dmbaturin** [comment]
Sorry for the late reply, I've been a bit overloaded lately.

Yes, the reason was that the main page loading function was interpreting page source files as if they were complete documents even in generator mode, which indeed led to edge cases with some tags like `<style>` (although I'd argue that lambdasoup's behavior for those is odd — I'll look into it).

If you don't have a build environment, I can make a test build if you want to test it.

**Comment by delan** [comment]
Thank you for the fix! I tested it on my site without [the workaround](https://github.com/delan/funny.computer.daz.cat/commit/498850d65970bc56e05916af4a67b1c0b22a96a5) and it worked great:

```diff
diff --git a/production/test.html b/production/test.html
index 99f603f..af326b2 100644
--- a/production/test.html
+++ b/production/test.html
@@ -17,23 +17,23 @@
 <main><style>
     * { image-rendering: auto; }
     :root { image-rendering: pixelated; background: url(/common/bg16e2x.png); }
     @media (min-width: 960px) {
         :root { background-size: 32px; }
     }
 
     main canvas, main img {
         image-rendering: pixelated;
         width: 66px;
         height: 66px;
     }
     main canvas {
         border: 2px solid rebeccapurple;
     }
     main img {
         border: 2px solid green;
     }
 </style>
-<body><p><canvas width="16" height="16"></canvas> = candidate
+<p><canvas width="16" height="16"></canvas> = candidate
 </p><p><img id="result" width="16" height="16"> = result
 <script>
     const main = document.querySelector("main");
@@ -143,7 +143,7 @@
         return new Promise(resolve => requestAnimationFrame(t => resolve(t)));
     }
 </script>
-</p></body></main>
+</p></main>
 <hr><footer>
 <p>last modified <span id="mtime">2024-01-13T17:08Z</span>
 </p><div class="_88x31">
```
