### ISSUE TITLE
4.7.0: Calling plugins leads to "Duplicate 'inner_text' registered in module 'HTML'" (already fixed, but needs release)

### ISSUE THREAD

**Issue by artjomsimon** [PataphysicalSociety/soupault#59]
First of all, thank you for creating and maintaining this very useful tool.
This report is just a disguised attempt to nudge you to release Soupault 4.8.0 :)

Trying to call Soupault 4.7.0 while having any plugin referenced in the .toml file gives me this trace:

```
Fatal error: exception Failure("Duplicate 'inner_text' registered in module 'HTML'")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Dune__exe__Plugin_api.MakeLib.M.init in file "src/plugin_api.ml", line 832, characters 6-1023
Called from Lualib.Combine.C10.M.init in file "src/lualib.ml", line 320, characters 10-20
Called from Luainterp.Make.pre_mk in file "src/luainterp.ml", line 581, characters 6-15
Called from Luabaselib.Add.mk in file "src/luabaselib.ml", line 101, characters 18-29
Called from Dune__exe__Plugin_api.run_plugin in file "src/plugin_api.ml", line 1246, characters 18-25
Called from Dune__exe__Soupault.process_widgets in file "src/soupault.ml", line 343, characters 12-52
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 536, characters 12-66
Called from Dune__exe__Soupault.process_page in file "src/soupault.ml", line 548, characters 8-67
Called from Dune__exe__Soupault.process_index_files.(fun) in file "src/soupault.ml", line 854, characters 15-66
Called from Dune__exe__Utils.fold_left_result.(fun) in file "src/helpers/utils.ml", line 62, characters 15-22
Called from Dune__exe__Soupault.main in file "src/soupault.ml", line 1016, characters 25-91
Called from Dune__exe__Soupault in file "src/soupault.ml", line 1068, characters 12-28
```

This is most probably already solved since [removing the duplicate "inner_html" in plugin_api.ml](https://github.com/PataphysicalSociety/soupault/commit/c9a0d44097295822960ce297949ab265d0c4179e#diff-56e5622db73dfbc592a0aea51aabe44041b2d94d8c72aacb28f5e4842d9a8a6b), but is broken in the current latest version.

**Comment by dmbaturin** [comment]
I'll make 4.8.0 release over the weekend. I planned to make it over a month ago, but I got sidetracked with trying to implement some new features that turned out unexpectedly tricky, and then got overloaded with other things... but it's certainly time to make the binaries finally, and everything else can go to 4.9.0 (or, possibly, 5.0.0).

**Comment by artjomsimon** [comment]
Thank you so much @dmbaturin for releaseing 4.8.0 ❤️ 
If you get to it, could you please also update the OPAM release? 😅 
I found it very convenient to use a generic Linux Docker image in my CI pipeline, install OPAM via the distro's package manager, and let it install soupault.

Thank you again so much!

**Comment by dmbaturin** [comment]
Sorry, I forgot to make an OPAM release. I made a PR today, thanks for the reminder!
