### ISSUE TITLE
Missing :has selector

### ISSUE THREAD

**Issue by justbhoot** [PataphysicalSociety/soupault#60]
I am attempting the following:

```
[widgets.table-of-contents]
widget = "toc"
selector = "hgroup:has(h1)"
action = "insert_after"
```

soupault throws an error `Fatal error: exception Soup.Parse_error("unknown pseudo-class or pseudo-element ':has'")`

I have a feeling though that this error comes from whichever underlying parsing library is being used.

**Comment by dmbaturin** [comment]
Yes, this is an issue for @aantron and lambdasoup. It's probably simple to implement, I may take a look if he doesn't have much time now, but please create an issue there first.

**Comment by jyssh** [comment]
I wanted to get my hands wet anyway, so I did it myself. PR: https://github.com/aantron/lambdasoup/pull/56

**Comment by justbhoot** [comment]
PR has been merged. Closing this issue.
