### ISSUE TITLE
Preprocessing CSS

### ISSUE THREAD

**Issue by podikoglou** [PataphysicalSociety/soupault#62]
Is there any way to run preprocessors on non-markup files like CSS? -- My use case is to run [Lighting css](https://lightningcss.dev/docs.html#from-the-cli) so that my css can use newer CSS features.

**Comment by dmbaturin** [comment]
At a glance, the built-in asset preprocessor functionality (https://soupault.app/reference-manual/#asset-processing) should be enough — or am I missing anything?

**Comment by podikoglou** [comment]
I looked through the docs but I guess I missed it

Thank you!
