### ISSUE TITLE
[v4.11.0] Could we have minisigs, please?

### ISSUE THREAD

**Issue by kseistrup** [PataphysicalSociety/soupault#72]
The minisigs have been incredibly helpful when packaging soupault for ArchLinux/AUR, is there a chance we could have them back? :pray:

**Comment by dmbaturin** [comment]
Sorry, that was a mix-up on my side! They are in [https://github.com/PataphysicalSociety/soupault/releases/tag/4.11.0] and on the web server now.

**Comment by kseistrup** [comment]
Great, thanks! :+1:
